<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercise-09</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Exercise-09_files/libs/clipboard/clipboard.min.js"></script>
<script src="Exercise-09_files/libs/quarto-html/quarto.js"></script>
<script src="Exercise-09_files/libs/quarto-html/popper.min.js"></script>
<script src="Exercise-09_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Exercise-09_files/libs/quarto-html/anchor.min.js"></script>
<link href="Exercise-09_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Exercise-09_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Exercise-09_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Exercise-09_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Exercise-09_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise-09</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="coding-challenge-practice-simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="coding-challenge-practice-simple-linear-regression">Coding challenge: <strong>Practice Simple Linear Regression</strong></h2>
<p><strong>Step 1:</strong> Do a quick exploratory data analysis where you generate the five-number summary (median, minimum and maximum and 1st and 3rd quartile values), plus mean and standard deviation, for each quantitative variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Street_et_al_2017.csv"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 301 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Species, Taxonomic_group
dbl (11): Social_learning, Research_effort, ECV, Group_size, Gestation, Wean...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>quant_vars <span class="ot">&lt;-</span> <span class="fu">select_if</span>(d, is.numeric) <span class="co"># Select quantitative variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform exploratory data analysis</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(quant_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">quant_vars</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">301</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Social_learning</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: right;">16.51</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">214.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Research_effort</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">38.76</td>
<td style="text-align: right;">80.59</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">37.75</td>
<td style="text-align: right;">755.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ECV</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">68.49</td>
<td style="text-align: right;">82.84</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">11.82</td>
<td style="text-align: right;">58.55</td>
<td style="text-align: right;">86.20</td>
<td style="text-align: right;">491.27</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Group_size</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">13.26</td>
<td style="text-align: right;">15.20</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.12</td>
<td style="text-align: right;">7.50</td>
<td style="text-align: right;">18.23</td>
<td style="text-align: right;">91.20</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gestation</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">164.50</td>
<td style="text-align: right;">38.00</td>
<td style="text-align: right;">59.99</td>
<td style="text-align: right;">138.35</td>
<td style="text-align: right;">166.03</td>
<td style="text-align: right;">183.26</td>
<td style="text-align: right;">274.78</td>
<td style="text-align: left;">▁▅▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weaning</td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">311.09</td>
<td style="text-align: right;">253.08</td>
<td style="text-align: right;">40.00</td>
<td style="text-align: right;">121.66</td>
<td style="text-align: right;">234.16</td>
<td style="text-align: right;">388.78</td>
<td style="text-align: right;">1260.81</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longevity</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">331.97</td>
<td style="text-align: right;">165.67</td>
<td style="text-align: right;">103.00</td>
<td style="text-align: right;">216.00</td>
<td style="text-align: right;">301.20</td>
<td style="text-align: right;">393.30</td>
<td style="text-align: right;">1470.00</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex_maturity</td>
<td style="text-align: right;">194</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">1480.23</td>
<td style="text-align: right;">999.23</td>
<td style="text-align: right;">283.18</td>
<td style="text-align: right;">701.52</td>
<td style="text-align: right;">1427.17</td>
<td style="text-align: right;">1894.11</td>
<td style="text-align: right;">5582.93</td>
<td style="text-align: left;">▇▆▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Body_mass</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">6795.18</td>
<td style="text-align: right;">14229.83</td>
<td style="text-align: right;">31.23</td>
<td style="text-align: right;">739.44</td>
<td style="text-align: right;">3553.50</td>
<td style="text-align: right;">7465.00</td>
<td style="text-align: right;">130000.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maternal_investment</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">478.64</td>
<td style="text-align: right;">292.07</td>
<td style="text-align: right;">99.99</td>
<td style="text-align: right;">255.88</td>
<td style="text-align: right;">401.35</td>
<td style="text-align: right;">592.22</td>
<td style="text-align: right;">1492.30</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Repro_lifespan</td>
<td style="text-align: right;">206</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">9064.97</td>
<td style="text-align: right;">4601.57</td>
<td style="text-align: right;">2512.16</td>
<td style="text-align: right;">6126.22</td>
<td style="text-align: right;">8325.89</td>
<td style="text-align: right;">10716.60</td>
<td style="text-align: right;">39129.57</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Step 2:</strong> From this dataset, plot brain size (<strong>ECV</strong>) as a function of social group size (<strong>Group_size</strong>), longevity (<strong>Longevity</strong>), juvenile period length (<strong>Weaning</strong>), and reproductive lifespan (<strong>Repro_lifespan</strong>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot for brain size vs. social group size </span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> Group_size, <span class="at">y =</span> ECV)) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Brain Size vs. Social Group Size"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Social Group Size"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Brain Size (ECV)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Exercise-09_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot for brain size vs. longevity </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> Longevity, <span class="at">y =</span> ECV)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Brain Size vs. Longevity"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Longevity"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Brain Size (ECV)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Exercise-09_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot for brain size vs. juvenile period length </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> Weaning, <span class="at">y =</span> ECV)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Brain Size vs. Juvenile Period Length"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Juvenile Period Length"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Brain Size (ECV)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Exercise-09_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot for brain size vs. reproductive lifespan </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> Repro_lifespan, <span class="at">y =</span> ECV)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Brain Size vs. Reproductive Lifespan"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reproductive Lifespan"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Brain Size (ECV)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Exercise-09_files/figure-html/unnamed-chunk-2-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>There is positive linear relationship of brain size (ECV) with social group size (Group_size), longevity (Longevity), juvenile period length (Weaning), and reproductive lifespan (Repro_lifespan).</strong></p>
<p><strong>Step 3</strong>:Derive by hand the ordinary least squares regression coefficients B1 and B0 for ECV as a function of social group size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Street_et_al_2017.csv"</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 301 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Species, Taxonomic_group
dbl (11): Social_learning, Research_effort, ECV, Group_size, Gestation, Wean...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  Species       Taxonomic_group Social_learning Research_effort   ECV Group_size
  &lt;chr&gt;         &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1 Allenopithec… Catarrhini                    0               6  58.0       40  
2 Allocebus_tr… Catarrhini                    0               6  NA          1  
3 Alouatta_bel… Platyrrhini                   0              15  52.8        7.4
4 Alouatta_car… Platyrrhini                   0              45  52.6        8.9
5 Alouatta_gua… Platyrrhini                   0              37  51.7        7.4
6 Alouatta_pal… Platyrrhini                   3              79  49.9       13.1
# ℹ 7 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">names</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Species"             "Taxonomic_group"     "Social_learning"    
 [4] "Research_effort"     "ECV"                 "Group_size"         
 [7] "Gestation"           "Weaning"             "Longevity"          
[10] "Sex_maturity"        "Body_mass"           "Maternal_investment"
[13] "Repro_lifespan"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(s <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(ECV, Group_size) <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">mutate</span>(<span class="at">logECV =</span> <span class="fu">log</span>(ECV), <span class="at">logGS =</span> <span class="fu">log</span>(Group_size)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 151 × 15
   Species      Taxonomic_group Social_learning Research_effort   ECV Group_size
   &lt;chr&gt;        &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1 Allenopithe… Catarrhini                    0               6 58.0       40   
 2 Alouatta_be… Platyrrhini                   0              15 52.8        7.4 
 3 Alouatta_ca… Platyrrhini                   0              45 52.6        8.9 
 4 Alouatta_gu… Platyrrhini                   0              37 51.7        7.4 
 5 Alouatta_pa… Platyrrhini                   3              79 49.9       13.1 
 6 Alouatta_pi… Platyrrhini                   0              25 51.1        5.5 
 7 Alouatta_se… Platyrrhini                   0              82 55.2        7.9 
 8 Aotus_azarai Platyrrhini                   0              22 20.7        4.1 
 9 Aotus_trivi… Platyrrhini                   0              58 16.8        3.15
10 Arctocebus_… Strepsirhini                  0               1  6.92       1   
# ℹ 141 more rows
# ℹ 9 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;, logECV &lt;dbl&gt;, logGS &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># Dervice by hand ordinary least square fitting B1 nad B0 for log(ECV) ~logBody_mass)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># CALCULATE B1</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>(b1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(s<span class="sc">$</span>logECV, s<span class="sc">$</span>logGS)<span class="sc">/</span><span class="fu">var</span>(s<span class="sc">$</span>logGS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7078342</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate B0</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>(b0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(s<span class="sc">$</span>logECV)<span class="sc">-</span> b1<span class="sc">*</span> <span class="fu">mean</span>(s<span class="sc">$</span>logGS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.145548</code></pre>
</div>
</div>
<p><strong>Step 4</strong>: Confirm that you get the same results using the <code>lm()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(m <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span>logGS, <span class="at">data =</span> s))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logECV ~ logGS, data = s)

Coefficients:
(Intercept)        logGS  
     2.1455       0.7078  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logECV ~ logGS, data = s)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3777 -0.4331  0.0553  0.4056  3.7877 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.14555    0.14177   15.13   &lt;2e-16 ***
logGS        0.70783    0.06075   11.65   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9005 on 149 degrees of freedom
Multiple R-squared:  0.4768,    Adjusted R-squared:  0.4733 
F-statistic: 135.8 on 1 and 149 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>The both <code>lm()</code> function and manual calculations yield the same result.</strong></p>
<p><strong>Step 5</strong>: Repeat the analysis above for three different major radiations of primates - “catarrhines”, “platyrrhines”, and “strepsirhines”) separately. These are stored in the variable <strong>Taxonomic_group</strong>. Do your regression coefficients differ among groups? How might you determine this?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Street_et_al_2017.csv"</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 301 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Species, Taxonomic_group
dbl (11): Social_learning, Research_effort, ECV, Group_size, Gestation, Wean...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  Species       Taxonomic_group Social_learning Research_effort   ECV Group_size
  &lt;chr&gt;         &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1 Allenopithec… Catarrhini                    0               6  58.0       40  
2 Allocebus_tr… Catarrhini                    0               6  NA          1  
3 Alouatta_bel… Platyrrhini                   0              15  52.8        7.4
4 Alouatta_car… Platyrrhini                   0              45  52.6        8.9
5 Alouatta_gua… Platyrrhini                   0              37  51.7        7.4
6 Alouatta_pal… Platyrrhini                   3              79  49.9       13.1
# ℹ 7 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Species"             "Taxonomic_group"     "Social_learning"    
 [4] "Research_effort"     "ECV"                 "Group_size"         
 [7] "Gestation"           "Weaning"             "Longevity"          
[10] "Sex_maturity"        "Body_mass"           "Maternal_investment"
[13] "Repro_lifespan"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove missing variables</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(ECV, Group_size) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">logECV =</span> <span class="fu">log</span>(ECV), <span class="at">logGS =</span> <span class="fu">log</span>(Group_size))</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset data for each taxonomic group</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>strepsirhini_data <span class="ot">&lt;-</span> s <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Taxonomic_group <span class="sc">==</span> <span class="st">"Strepsirhini"</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>catarrhini_data <span class="ot">&lt;-</span> s <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Taxonomic_group <span class="sc">==</span> <span class="st">"Catarrhini"</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>platyrrhini_data <span class="ot">&lt;-</span> s <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Taxonomic_group <span class="sc">==</span> <span class="st">"Platyrrhini"</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression models for each taxonomic group</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>model_strepsirhini <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> strepsirhini_data)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>model_catarrhini <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> catarrhini_data)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>model_platyrrhini <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> platyrrhini_data)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display regression summaries</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_strepsirhini)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logECV ~ logGS, data = strepsirhini_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.89775 -0.42666  0.05441  0.47098  2.00196 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.8014     0.1404  12.832  &lt; 2e-16 ***
logGS         0.6282     0.1233   5.093 7.08e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7294 on 44 degrees of freedom
Multiple R-squared:  0.3709,    Adjusted R-squared:  0.3566 
F-statistic: 25.94 on 1 and 44 DF,  p-value: 7.076e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_catarrhini)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logECV ~ logGS, data = catarrhini_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.57941 -0.27722 -0.09538  0.12207  1.65274 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.556383   0.171841  26.515   &lt;2e-16 ***
logGS       -0.007746   0.060611  -0.128    0.899    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4606 on 68 degrees of freedom
Multiple R-squared:  0.0002401, Adjusted R-squared:  -0.01446 
F-statistic: 0.01633 on 1 and 68 DF,  p-value: 0.8987</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_platyrrhini)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logECV ~ logGS, data = platyrrhini_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.4893 -0.7408  0.1732  0.7434  1.1986 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.4767     0.4682   3.154 0.003425 ** 
logGS         0.8040     0.1958   4.106 0.000249 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8125 on 33 degrees of freedom
Multiple R-squared:  0.3381,    Adjusted R-squared:  0.318 
F-statistic: 16.86 on 1 and 33 DF,  p-value: 0.000249</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare regression coefficients among groups</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>coefficients_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Taxonomic_group =</span> <span class="fu">c</span>(<span class="st">"Strepsirhini"</span>, <span class="st">"Catarrhini"</span>, <span class="st">"Platyrrhini"</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">B1 =</span> <span class="fu">c</span>(<span class="fu">coef</span>(model_strepsirhini)[<span class="st">"logGS"</span>], <span class="fu">coef</span>(model_catarrhini)[<span class="st">"logGS"</span>], <span class="fu">coef</span>(model_platyrrhini)[<span class="st">"logGS"</span>])</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>coefficients_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Taxonomic_group           B1
1    Strepsirhini  0.628212872
2      Catarrhini -0.007745779
3     Platyrrhini  0.803971876</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform ANOVA to test if regression coefficients differ among groups</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(logECV <span class="sc">~</span> Taxonomic_group <span class="sc">*</span> logGS, <span class="at">data =</span> s)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Taxonomic_group         2 146.37   73.18  177.97  &lt; 2e-16 ***
logGS                   1  11.38   11.38   27.66 5.08e-07 ***
Taxonomic_group:logGS   2  13.56    6.78   16.49 3.53e-07 ***
Residuals             145  59.62    0.41                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>The</strong> <strong>difference of regression coefficient among three taxonomic groups has been determined using ANOVA. The ANOVA analysis revealed statistically significant variations in regression coefficients among the three taxonomic groups, as indicated by a (F(1,33) = 16.86 , p =0.0002).</strong></p>
<p><strong>Step 6:</strong> For your first regression of ECV on social group size, calculate the standard error for the slope coefficient, the 95% CI, and the <em>p</em> value associated with this coefficient by hand. Also extract this same information from the results of running the <code>lm()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Street_et_al_2017.csv"</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 301 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Species, Taxonomic_group
dbl (11): Social_learning, Research_effort, ECV, Group_size, Gestation, Wean...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  Species       Taxonomic_group Social_learning Research_effort   ECV Group_size
  &lt;chr&gt;         &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1 Allenopithec… Catarrhini                    0               6  58.0       40  
2 Allocebus_tr… Catarrhini                    0               6  NA          1  
3 Alouatta_bel… Platyrrhini                   0              15  52.8        7.4
4 Alouatta_car… Platyrrhini                   0              45  52.6        8.9
5 Alouatta_gua… Platyrrhini                   0              37  51.7        7.4
6 Alouatta_pal… Platyrrhini                   3              79  49.9       13.1
# ℹ 7 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">names</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Species"             "Taxonomic_group"     "Social_learning"    
 [4] "Research_effort"     "ECV"                 "Group_size"         
 [7] "Gestation"           "Weaning"             "Longevity"          
[10] "Sex_maturity"        "Body_mass"           "Maternal_investment"
[13] "Repro_lifespan"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(s <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(ECV, Group_size) <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">mutate</span>(<span class="at">logECV =</span> <span class="fu">log</span>(ECV), <span class="at">logGS =</span> <span class="fu">log</span>(Group_size)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 151 × 15
   Species      Taxonomic_group Social_learning Research_effort   ECV Group_size
   &lt;chr&gt;        &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1 Allenopithe… Catarrhini                    0               6 58.0       40   
 2 Alouatta_be… Platyrrhini                   0              15 52.8        7.4 
 3 Alouatta_ca… Platyrrhini                   0              45 52.6        8.9 
 4 Alouatta_gu… Platyrrhini                   0              37 51.7        7.4 
 5 Alouatta_pa… Platyrrhini                   3              79 49.9       13.1 
 6 Alouatta_pi… Platyrrhini                   0              25 51.1        5.5 
 7 Alouatta_se… Platyrrhini                   0              82 55.2        7.9 
 8 Aotus_azarai Platyrrhini                   0              22 20.7        4.1 
 9 Aotus_trivi… Platyrrhini                   0              58 16.8        3.15
10 Arctocebus_… Strepsirhini                  0               1  6.92       1   
# ℹ 141 more rows
# ℹ 9 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;, logECV &lt;dbl&gt;, logGS &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1 Manually calculate standard error, 95% CI, and p-value</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(s)  <span class="co">#</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>(t_value <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>))  <span class="co"># 2-tailed t-value for 95% CI</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.976013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate B1</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>(b1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(s<span class="sc">$</span>logECV, s<span class="sc">$</span>logGS)<span class="sc">/</span><span class="fu">var</span>(s<span class="sc">$</span>logGS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7078342</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate B0</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>(b0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(s<span class="sc">$</span>logECV)<span class="sc">-</span> b1<span class="sc">*</span> <span class="fu">mean</span>(s<span class="sc">$</span>logGS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.145548</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate residuals</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> s<span class="sc">$</span>logECV <span class="sc">-</span> (b0 <span class="sc">+</span> b1 <span class="sc">*</span> s<span class="sc">$</span>logGS)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>se_by_hand <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(residuals<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n <span class="sc">-</span> <span class="dv">2</span>)) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>((s<span class="sc">$</span>logGS <span class="sc">-</span> <span class="fu">mean</span>(s<span class="sc">$</span>logGS))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% Confidence Interval</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>ci_by_hand <span class="ot">&lt;-</span> <span class="fu">c</span>(b1 <span class="sc">-</span> t_value <span class="sc">*</span> se_by_hand, b1 <span class="sc">+</span> t_value <span class="sc">*</span> se_by_hand)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="co"># P-value</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> b1 <span class="sc">/</span> se_by_hand</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>p_value_by_hand <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_stat), <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results calculated by hand</span></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Results calculated by hand:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Results calculated by hand:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard Error of Coefficient (B1):"</span>, se_by_hand, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard Error of Coefficient (B1): 0.06074842 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% Confidence Interval for Coefficient (B1): ["</span>, ci_by_hand[<span class="dv">1</span>], <span class="st">","</span>, ci_by_hand[<span class="dv">2</span>], <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% Confidence Interval for Coefficient (B1): [ 0.5877945 , 0.8278739 ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value for Coefficient (B1):"</span>, p_value_by_hand, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value for Coefficient (B1): 1.035862e-22 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2 Extract coefficient standard error, 95% CI, and p-value from lm() results</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> s)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate SE, 95%CI and p-value using lm()</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>se_coef <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coef[<span class="dv">2</span>, <span class="st">"Std. Error"</span>]</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(model)[<span class="dv">2</span>, ]</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coef[<span class="dv">2</span>, <span class="st">"Pr(&gt;|t|)"</span>]</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display lm() results</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Results from lm() function:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Results from lm() function:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard Error of Coefficient (B1):"</span>, se_coef, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard Error of Coefficient (B1): 0.06074842 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% Confidence Interval for Coefficient (B1): ["</span>, ci[<span class="dv">1</span>], <span class="st">","</span>, ci[<span class="dv">2</span>], <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% Confidence Interval for Coefficient (B1): [ 0.5877945 , 0.8278739 ]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value for Coefficient (B1):"</span>, p_value, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value for Coefficient (B1): 1.035862e-22 </code></pre>
</div>
</div>
<p><strong>The manually calculated values for standard error, 95% confidence interval, and p-value using the formula match with the values obtained using the <code>lm()</code> function. This consistency indicates that both methods are producing equivalent results for the slope coefficient.</strong></p>
<p><strong>Step 7</strong>: Use a permutation approach with 1000 permutations to generate a null sampling distribution for the <strong>slope coefficient</strong>. What is it that you need to permute? What is the p value associated with your original slope coefficient? You can use either the percentile method (i.e., using quantiles from the actual permutation-based null sampling distribution) or a theory-based method (i.e., using the standard deviation of the permutation-based null sampling distribution as the estimate of the standard error, along with a normal or t distribution), or both, to calculate this p value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the number of permutations</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the original slope coefficient</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">=</span> <span class="fl">0.71</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>original_b1 <span class="ot">&lt;-</span> b1</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty vector to store permuted slope coefficients</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>permuted_b1 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform permutations and calculate slope coefficients</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Set seed for reproducibility</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Permute the response variable</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  permuted_response <span class="ot">&lt;-</span> <span class="fu">sample</span>(s<span class="sc">$</span>logECV)</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fit a linear model with permuted data</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>  permuted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(permuted_response <span class="sc">~</span> s<span class="sc">$</span>logGS)</span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store the permuted slope coefficient</span></span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  permuted_b1[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(permuted_model)[<span class="dv">2</span>]</span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the p-value using the percentile method</span></span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>p_value_percentile <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">abs</span>(permuted_b1) <span class="sc">&gt;=</span> <span class="fu">abs</span>(original_b1)) <span class="sc">/</span> n</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value (Percentile Method):"</span>, p_value_percentile, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value (Percentile Method): 0 </code></pre>
</div>
</div>
<p><strong>In a permutation approach, the idea is to randomly shuffle or permute the values of the response variable (in this case, <code>logECV</code>) while keeping the predictor variable (in this case, <code>logGS</code>) unchanged. This process helps generate a null sampling distribution under the assumption that there is no true relationship between the response and predictor variables.In the steps above, we used the percentile</strong> <strong>method which involves comparing the observed statistic (in this case, the absolute value of the original slope coefficient) with the distribution of values obtained from permutations. The proportion of permuted values as extreme or more extreme than the observed value provides the p-value. We obtain the p-value of 0.00 which suggests a significant association between the variables (ECV and group_size).</strong></p>
<p><strong>Step 8:</strong> Use bootstrapping to generate a 95% CI for your estimate of the slope coefficient using both the percentile method and the theory-based method (i.e., using on the standard deviation of the bootstrapped sampling distribution as an estimate of the standard error). Do these CIs suggest that your slope coefficient is different from zero?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Street_et_al_2017.csv"</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(f, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 301 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Species, Taxonomic_group
dbl (11): Social_learning, Research_effort, ECV, Group_size, Gestation, Wean...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  Species       Taxonomic_group Social_learning Research_effort   ECV Group_size
  &lt;chr&gt;         &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1 Allenopithec… Catarrhini                    0               6  58.0       40  
2 Allocebus_tr… Catarrhini                    0               6  NA          1  
3 Alouatta_bel… Platyrrhini                   0              15  52.8        7.4
4 Alouatta_car… Platyrrhini                   0              45  52.6        8.9
5 Alouatta_gua… Platyrrhini                   0              37  51.7        7.4
6 Alouatta_pal… Platyrrhini                   3              79  49.9       13.1
# ℹ 7 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">names</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Species"             "Taxonomic_group"     "Social_learning"    
 [4] "Research_effort"     "ECV"                 "Group_size"         
 [7] "Gestation"           "Weaning"             "Longevity"          
[10] "Sex_maturity"        "Body_mass"           "Maternal_investment"
[13] "Repro_lifespan"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>(s <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(ECV, Group_size) <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">mutate</span>(<span class="at">logECV =</span> <span class="fu">log</span>(ECV), <span class="at">logGS =</span> <span class="fu">log</span>(Group_size)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 151 × 15
   Species      Taxonomic_group Social_learning Research_effort   ECV Group_size
   &lt;chr&gt;        &lt;chr&gt;                     &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1 Allenopithe… Catarrhini                    0               6 58.0       40   
 2 Alouatta_be… Platyrrhini                   0              15 52.8        7.4 
 3 Alouatta_ca… Platyrrhini                   0              45 52.6        8.9 
 4 Alouatta_gu… Platyrrhini                   0              37 51.7        7.4 
 5 Alouatta_pa… Platyrrhini                   3              79 49.9       13.1 
 6 Alouatta_pi… Platyrrhini                   0              25 51.1        5.5 
 7 Alouatta_se… Platyrrhini                   0              82 55.2        7.9 
 8 Aotus_azarai Platyrrhini                   0              22 20.7        4.1 
 9 Aotus_trivi… Platyrrhini                   0              58 16.8        3.15
10 Arctocebus_… Strepsirhini                  0               1  6.92       1   
# ℹ 141 more rows
# ℹ 9 more variables: Gestation &lt;dbl&gt;, Weaning &lt;dbl&gt;, Longevity &lt;dbl&gt;,
#   Sex_maturity &lt;dbl&gt;, Body_mass &lt;dbl&gt;, Maternal_investment &lt;dbl&gt;,
#   Repro_lifespan &lt;dbl&gt;, logECV &lt;dbl&gt;, logGS &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> s)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty vector to store bootstrapped slope coefficients</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>bootstrapped_b1 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform bootstrapping and calculate slope coefficients</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Set seed for reproducibility</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Generate a bootstrap sample</span></span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>  bootstrap_sample <span class="ot">&lt;-</span> s[<span class="fu">sample</span>(<span class="fu">nrow</span>(s), <span class="at">replace =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fit a linear model with the bootstrap sample</span></span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>  bootstrap_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(logECV <span class="sc">~</span> logGS, <span class="at">data =</span> bootstrap_sample)</span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store the bootstrapped slope coefficient</span></span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>  bootstrapped_b1[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(bootstrap_model)[<span class="dv">2</span>]</span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate 95% CI using the percentile method</span></span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>ci_percentile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(bootstrapped_b1, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate 95% CI using the theory-based method</span></span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>se_bootstrapped <span class="ot">&lt;-</span> <span class="fu">sd</span>(bootstrapped_b1)</span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>ci_theory <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(bootstrapped_b1) <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_bootstrapped, <span class="fu">mean</span>(bootstrapped_b1) <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_bootstrapped)</span>
<span id="cb86-28"><a href="#cb86-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-29"><a href="#cb86-29" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% CI (Percentile Method):"</span>, ci_percentile, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI (Percentile Method): 0.5770865 0.8253781 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% CI (Theory-Based Method):"</span>, ci_theory, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI (Theory-Based Method): 0.5823355 0.8288691 </code></pre>
</div>
</div>
<ul>
<li><strong>The 95% CI using Percentile Method are (0.5770865, 0.8253781), and the 95% CI (Theory-Based Method) are (0.5823355, 0.8288691)</strong>. <strong>Since the confidence intervals using both percentile method and theory based method do not include zero, it suggests that the slope coefficient is significantly different from zero. This means that we have evidence to reject the null hypothesis that the true value of the slope coefficient is zero.</strong></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>